before_script:
  - cd "$CI_PROJECT_DIR/Source/"
  - bundle install

# Сборка для QA
qa:
  only:
    - /^qa\/[0-9]{1,}.[0-9]{1,}(.[0-9]{1,})?\/[0-9]{1,}$/ # qa/1.0.0/99
  except:
    - branches
    - triggers
  script:
    - bundle exec fastlane ci
  tags:
    - ios-qa-release
    
# Запуск всех тестов кроме UI-тестов
test:
  only:
    - /^fix|bugfix|refactor|feature\/.+$/
  except:
    - schedules
  script:
    - bundle exec fastlane test ui_tests:false
  tags:
    - ios-test
  allow_failure: false

# Запуск UI-тестов по расписанию
ui_test:
  only:
    - schedules
  script:
    - bundle exec fastlane test ui_tests:true
  tags:
    - ios-test
  allow_failure: false
