source "https://rubygems.org"

gem "cocoapods"
gem "fastlane"
gem 'danger'
gem 'danger-gitlab'
gem 'danger-xcov'
gem 'danger-xcode_summary'
gem 'danger-swiftlint'
gem 'xcpretty-json-formatter'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
