platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

#Библиотеки располагаются в алфавитном порядке
def main_pods
  pod 'AlamofireImage'
  pod 'InputMask'
  pod 'KeychainAccess'
  pod 'SwiftLint'
end

target 'OmegaBank' do
  project 'OmegaBank.xcodeproj'
  main_pods
end

target 'OmegaBankAPI' do
  use_frameworks!

  pod 'Alamofire', '~> 4.8'

  target 'OmegaBankAPITests' do
    inherit! :search_paths
  end
end

target 'OmegaBankUITests' do
  project 'OmegaBank.xcodeproj'
  pod 'Catbird'
end
